language: node_js
node_js:
  "lts/*"
before_script:
  - yarn global add docusaurus-init
before_install:
  - cd website
script: yarn publish-gh-pages
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  on:
    branch: source