language: node_js
node_js:
  "lts/*"
before_script:
  - yarn global add docusaurus-init
before_install:
  - cd website
  - git config --global user.name $GIT_USER_NAME
  - git config --global user.name $GIT_USER_EMAIL
script: CURRENT_BRANCH=source yarn publish-gh-pages
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  on:
    branch: source
